name: markdown to PDF

on:
  workflow_dispatch: # このワークフローを手動で起動できるように設定します。

permissions:
  contents: read

jobs:
  markdown_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Install pdfLatex
        run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - name: Find Markdown files
        id: find_markdown
        run: |
          find . -name "*.md" -print0 | xargs -0 printf "%s\n" > markdown_files.txt
          echo "::set-output name=markdown_file_list::$(cat markdown_files.txt)"
      - name: show markdown_files.txt
        run: cat -A markdown_files.txt
      - name: Convert Markdown to PDF with pandoc
        run: |
          markdown_files=$(cat markdown_files.txt)
          set | grep markdown
          if [ -n "$markdown_files" ]; then
            while IFS= read -r file; do
              pdf_file="${file%.md}.pdf"
              echo "Converting '$file' to '$pdf_file'"
              pandoc "$file" -o "$pdf_file"
              if [ $? -eq 0 ]; then
                echo "Successfully converted '$file' to '$pdf_file'"
              else
                echo "Failed to convert '$file'"
              fi
            done <<< "$markdown_files"
          else
            echo "No Markdown files found."
          fi
      - name: find pdf file
        run: find . -name "*.md"
      - name: current dir show
        run: find . -name "*.pdf"
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-artifacts
          path: ./*.pdf
